### ISSUE TITLE
malloc

### ISSUE THREAD

**Issue by backfromhiatus** [robotman2412/thecpuproject#2]
I still don't get how memory allocation works. Can you explain it to me? I'm working on a hobby OS, so...

**Comment by robotman2412** [comment]
First of all, what is your programming experience?
I don't know malloc isn't enough detail.
Did you read my website at https://robot.scheffers.net/project/gr8nix ?

**Comment by backfromhiatus** [comment]
Yup

**Comment by backfromhiatus** [comment]
I've been programming for 1 or 2 years

**Comment by robotman2412** [comment]
Be more specific: what languages?
What have you programmed in the past?
Have you ever collaborated?

Also: assembly is pretty rough. I think you would do good to really get the hang of C++, followed by C first.

**Comment by backfromhiatus** [comment]
uhhh, heres my project, which is in assembly: https://github.com/Digital-Electronics-LLC/CrylonOS

I know, I know, it's sorta meh

**Comment by robotman2412** [comment]
You didn't fully answer my question.
Or rather, you only showed me one thing.
Are there more projects you've done in the past?

Also, why does your project say it's based on GR8NIX?
That should be inspired by (it looks like x86, a totally incompatible platform).

**Comment by backfromhiatus** [comment]
Right, I program in asm
And, no, I have not done any other OS projects except an emulator

**Comment by backfromhiatus** [comment]
I have programmed in puthon

**Comment by backfromhiatus** [comment]
I have not collabed

**Comment by backfromhiatus** [comment]
Except for a organization website

**Comment by backfromhiatus** [comment]
by the way, my OS is not x86 based

**Comment by backfromhiatus** [comment]
i actually used some instructions from your instruction set

**Comment by backfromhiatus** [comment]
Can you explain to me the Malloc section of the website?

**Comment by robotman2412** [comment]
In short: no.
I don't see a mention of any programming in either C it C++.
Python is a great language for beginners, but not for this type of thing.
When I said get comfortable with C and C++ i mean it.
It is a prerequisite for this.

I can recommend you to get an Arduino (https://store.arduino.cc/products/arduino-uno-rev3), and to watch some introductory C++ videos to go with it (https://youtu.be/fJWR7dBuc18).

I wish you the best of luck.

**Comment by backfromhiatus** [comment]
My avatar is the python logo
Also, Idk how to code I C or CPP
And, I'm not planning to use it

**Comment by robotman2412** [comment]
Then i cannot help you

**Comment by backfromhiatus** [comment]
Also, the reason why I don't wanna use C is because I wanna know HOW IT WORKS. It's a hobby OS that's supposed to teach me how OSes work. I might use C and write a compiler to translate it into RX(Red Xenon) machine code, which is my instruction set after 1.0.0, but for now...
