### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by backfromhiatus** [robotman2412/thecpuproject#4]
Iron man: sh*t!
Cap: Language!!!!

Robotman: FuckingTestBinary
Cap: Language!!!!

Just a small meme/Avengers Age of Ultron reference

**Comment by robotman2412** [comment]
This is not what GitHub issues are for

**Comment by robotman2412** [comment]
If you are not willing to accept my advice, then don't open new issues

**Comment by backfromhiatus** [comment]
kk
